/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.uni.importeapp.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import pe.uni.importe.dto.Importe;
import pe.uni.importe.service.ImporteService;

/**
 *
 * @author JSOSA
 */
public class ImporteView extends javax.swing.JFrame {

    /**
     * Creates new form ImporteView
     */
    public ImporteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtlimpiar = new javax.swing.JButton();
        txtProcesar = new javax.swing.JButton();
        txtsalir = new javax.swing.JButton();
        txttht = new javax.swing.JTextField();
        txtcdt = new javax.swing.JTextField();
        txtpph = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtimpuesto = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pago de trabajador: ");

        jLabel1.setText("Total horas trabajdas: ");

        jLabel2.setText("Cantidad dias trabajados: ");

        jLabel3.setText("Pago por horas: ");

        txtlimpiar.setText("LIMPIAR");
        txtlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlimpiarActionPerformed(evt);
            }
        });

        txtProcesar.setText("CALCULAR");
        txtProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcesarActionPerformed(evt);
            }
        });

        txtsalir.setText("SALIR");
        txtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalirActionPerformed(evt);
            }
        });

        txttht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthtActionPerformed(evt);
            }
        });
        txttht.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtthtKeyPressed(evt);
            }
        });

        txtcdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcdtActionPerformed(evt);
            }
        });
        txtcdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcdtKeyPressed(evt);
            }
        });

        txtpph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpphActionPerformed(evt);
            }
        });
        txtpph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpphKeyPressed(evt);
            }
        });

        jLabel4.setText("IMPUESTO A PAGAR:");

        jLabel5.setText("TOTAL A PAGAR: ");

        jLabel6.setText("DATOS:");

        jLabel7.setText("DATOS A PAGAR: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtProcesar)
                        .addGap(29, 29, 29)
                        .addComponent(txtlimpiar)
                        .addGap(27, 27, 27)
                        .addComponent(txtsalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(111, 111, 111))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtcdt)
                                    .addComponent(txttht, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(txtpph))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtimpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(txttotal))
                                .addGap(0, 44, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttht, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtimpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcdt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProcesar)
                            .addComponent(txtlimpiar)
                            .addComponent(txtsalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtpph, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalirActionPerformed
        dispose();
    }//GEN-LAST:event_txtsalirActionPerformed

    private void txtlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlimpiarActionPerformed
       limpiarDatos();
    }//GEN-LAST:event_txtlimpiarActionPerformed

    private void txtthtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthtActionPerformed
   
    }//GEN-LAST:event_txtthtActionPerformed

    private void txtcdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcdtActionPerformed
           

    }//GEN-LAST:event_txtcdtActionPerformed

    private void txtpphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpphActionPerformed
            

    }//GEN-LAST:event_txtpphActionPerformed

    private void txtProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcesarActionPerformed
       proceso();
    }//GEN-LAST:event_txtProcesarActionPerformed

    private void txtthtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtthtKeyPressed
      
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
txtcdt.requestFocus();

}

    }//GEN-LAST:event_txtthtKeyPressed

    private void txtcdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcdtKeyPressed
       if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
txtpph.requestFocus();
 }                                 
    }//GEN-LAST:event_txtcdtKeyPressed

    private void txtpphKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpphKeyPressed
           if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
txtProcesar.requestFocus();
txtProcesar.doClick();
 }   
    }//GEN-LAST:event_txtpphKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImporteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImporteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImporteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImporteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImporteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton txtProcesar;
    private javax.swing.JTextField txtcdt;
    private javax.swing.JTextField txtimpuesto;
    private javax.swing.JButton txtlimpiar;
    private javax.swing.JTextField txtpph;
    private javax.swing.JButton txtsalir;
    private javax.swing.JTextField txttht;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private void limpiarDatos() {
    
        txttht.setText(" ");
        txtcdt.setText(" ");
        txtpph.setText(" ");
        txtimpuesto.setText(" ");
        txttotal.setText(" ");
        txttht.requestFocus();
    }

    private void proceso() {
        
    //variables
    double tht,cdt,pph;
    double res;
  
    
    Importe imp = new Importe();
    
    //Datos
    tht=Double.parseDouble(txttht.getText());
    cdt=Double.parseDouble(txtcdt.getText());
    pph=Double.parseDouble(txtpph.getText());
    
    //Proceso
    imp.setTht(tht);
    imp.setCdt(cdt);
    imp.setPph(pph);
    
    ImporteService service= new ImporteService();
    imp=service.procesar(imp);
    
    
    
    //Reporte
    txttotal.setText(String.valueOf(imp.getTotalLiquido()));
    txtimpuesto.setText(String.valueOf(imp.getImpuesto()));
    
    if (imp.getIngreso() < 1500){
         JOptionPane.showMessageDialog(null, "El ingreso es menor de 1500");
    }
       
    
    }
}
