                                                                                                                                             /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.uni.proyectosunat.view;


import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pe.uni.proyectosunat.app.controller.ProyectoSunatController;
import pe.uni.proyectosunat.app.dto.ProyectoSunatDto;
import pe.uni.proyectosunat.service.ProyectoSunatService;
import static pe.uni.proyectosunat.service.ProyectoSunatService.ConectarSQLServer;
import pe.uni.proyectosunat.service.utilsJasperReport;

//import sun.net.www.protocol.http.HttpURLConnection;

/**
 *
 * @author DWIGHT
 */
public class OperacionSunatView extends javax.swing.JInternalFrame {

    /**
     * Creates new form OperacionSunat
     */
    public OperacionSunatView() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRentaBruta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRentaQuinta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGenerarPDF = new javax.swing.JButton();
        btnAbrirPDF = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        btnGenerarReporte = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("OPERACIONES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Simulador Renta de Cuarta y Quinta Categoría");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Renta Bruta obtenida por el ejercicio individual (Profesión, arte, ciencia u oficio)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Deducción (20% del monto consignado en la Cas. 107 - Máximo S/ 100,800)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Renta Neta obtenida por el ejercicio individual (Profesión, arte, ciencia u oficio)” Cas. 107-Cas.507 ");

        txtRentaBruta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total rentas de quinta categoría ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total rentas de cuarta y quinta categoría (Cas. 509 + Cas. 111) ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Deducción de 7 UIT (Hasta el límite resultante de la Cas. 510) ");

        txtRentaQuinta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("TOTAL RENTA NETA DE CUARTA Y QUINTA CATEGORÍA Cas. 510 – Cas. 511 - Cas. ABC) ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Sub total Cas. 512 – (Cas. 522 + Cas. 519) ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Impuesto a la Renta ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Renta Imponible de Trabajo y Fuente Extranjera ");

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setText(" ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Saldo de la Deuda Tributaria");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setText(" ");

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setText(" ");

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setText(" ");

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setText(" ");

        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setText(" ");

        lbl7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl7.setText(" ");

        lbl8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl8.setText(" ");

        lbl9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl9.setText(" ");

        btnProcesar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProcesar.setText("PROCESAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("NOMBRE:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnGenerarPDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        btnAbrirPDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAbrirPDF.setText("Abrir PDF");
        btnAbrirPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPDFActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("RUC/DNI");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("CELULAR");

        btnGenerarReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarReporte.setText("Generar");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRentaBruta)
                    .addComponent(txtRentaQuinta)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnProcesar)
                        .addGap(37, 37, 37)
                        .addComponent(btnGenerarReporte)
                        .addGap(64, 64, 64)
                        .addComponent(btnGenerarPDF)
                        .addGap(36, 36, 36)
                        .addComponent(btnAbrirPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRentaBruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRentaQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbl9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnGenerarPDF)
                    .addComponent(btnAbrirPDF)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGenerarReporte))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        //Variables
        double rentaCuarta, rentaQuinta;
        String n_doc_declarante, nombre,celular;
        //double deduccion, rentaNeta, totalrenta, deduccion2, totalcuartaquinta, cas_512,cas_513,cas_517,cas_120,cas_146;
        ProyectoSunatDto dto = new ProyectoSunatDto();
        
        //ProyectoSunatController controlador;
                
        //Datos
        rentaCuarta = Double.parseDouble(txtRentaBruta.getText());
        rentaQuinta = Double.parseDouble(txtRentaQuinta.getText());
        n_doc_declarante=txtRuc.getText();
        nombre=txtNombre.getText();
        celular=txtCelular.getText();
        //Proceso
        dto.setRenta_cuarta(rentaCuarta);
        dto.setRenta_quinta(rentaQuinta);
        
        ProyectoSunatService service = new ProyectoSunatService();
        dto = service.procesar(dto);
        
//        controlador = new ProyectoSunatController();
//        deduccion = controlador.deduccion(rentaCuarta);
//        rentaNeta = controlador.rentNeta(rentaCuarta);
//        totalrenta = controlador.totalRentas(rentaCuarta, rentaQuinta);
//        deduccion2 = controlador.deduccion2(rentaCuarta, rentaQuinta);
//        cas_512 = controlador.cas_512(rentaCuarta, rentaQuinta);
//        cas_513 = controlador.cas_513(rentaCuarta, rentaQuinta);
//        cas_517 = controlador.cas_513(rentaCuarta, rentaQuinta);
//        cas_120 = controlador.cas_120(rentaCuarta, rentaQuinta);
//        cas_146 = controlador.cas_120(rentaCuarta, rentaQuinta);


        //Reporte
        lbl1.setText(dto.getDeduccion()+"");
        lbl2.setText(dto.getRentaNeta()+"");
        lbl3.setText(dto.getTotalRentas()+"");
        lbl4.setText(dto.getDeduccion2()+"");
        lbl5.setText(dto.getCas_512()+"");
        lbl6.setText(dto.getCas_513()+"");
        lbl7.setText(dto.getCas_513()+"");
        lbl8.setText(dto.getCas_120()+"");
        lbl9.setText(dto.getCas_120()+"");
        
        
        //Insertar en base de datos
        Connection conn;
        try {
          
            conn = ConectarSQLServer();
                   
            String query="insert into db_fisca_exp.dbo.declarante (n_doc_declarante, nom_declarante,cell_declarante) \n" +
            "values ("+ n_doc_declarante+",'"+nombre+"' ,'"+celular+"')\n" ;
           
            String query2="   insert into db_fisca_exp.dbo.declaraciones (n_doc_declarante,anio,fecha,cas107,cas507,cas508,cas111,cas510,cas511,cas512,cas513,cas517,cas120,cas146)\n" +
            "  values ("+n_doc_declarante+",'2019',cast(getdate() as date),"+rentaCuarta+","+dto.getDeduccion()+",\n" +
            "	  "+dto.getRentaNeta()+","+rentaQuinta+","+dto.getTotalRentas()+","+dto.getDeduccion2()+","+dto.getCas_512()+","+dto.getCas_513()+","+dto.getCas_513()+","+dto.getCas_120()+","+dto.getCas_120()+" )";
 
            Statement stmt = conn.createStatement();
            try{
            stmt.executeUpdate(query);
            } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, ex, "Error bbb", JOptionPane.INFORMATION_MESSAGE);
            } 
            stmt.executeUpdate(query2);
            
            JOptionPane.showMessageDialog(this, "Se registro la declaración");
            
      
                
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error ", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error ", JOptionPane.INFORMATION_MESSAGE);
        } 
        
 
        
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        // TODO add your handling code here:
        try {
            generar(txtNombre.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OperacionSunatView.class.getName()).log(Level.SEVERE,null,ex);
        } 
        catch (DocumentException ex){
            Logger.getLogger(OperacionSunatView.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    private void btnAbrirPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPDFActionPerformed
        // TODO add your handling code here:
        if(!txtNombre.getText().isEmpty()){
            abrir(txtNombre.getText());
        }else{
            JOptionPane.showMessageDialog(null,"Campo nombre vacío\n No se encuentra el archivo con ese nombre"
                ,"Atencion",2);
        }
    }//GEN-LAST:event_btnAbrirPDFActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
        Reporte tReporte = new Reporte(this);
        tReporte.start();
        
    }//GEN-LAST:event_btnGenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPDF;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRentaBruta;
    private javax.swing.JTextField txtRentaQuinta;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables

    private void generar(String nombre) throws FileNotFoundException, DocumentException{
        if(!(txtNombre.getText().isEmpty()) ){
            
            FileOutputStream archivo = new FileOutputStream(nombre + ".pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            documento.open();
            
            Paragraph parrafo = new Paragraph("SIMULADORS SUNAT-RENTA CUARTA Y QUINTA CATEGORIA");
            parrafo.setAlignment(1);
            
            
            documento.add(parrafo);
            
            documento.add(new Paragraph("Nombre: " + txtNombre.getText()));
            documento.add(new Paragraph("Renta Bruta obtenida por el ejercicio individual (Profesión, arte, ciencia u oficio): "
                    + txtRentaBruta.getText()));
            documento.add(new Paragraph("Deducción (20% del monto consignado en la Cas. 107 - Máximo S/ 100,800): " 
                    + lbl1.getText()));
            documento.add(new Paragraph("Renta Neta obtenida por el ejercicio individual (Profesión, arte, ciencia u oficio)” Cas. 107-Cas.507 : " 
                    + lbl2.getText()));
            documento.add(new Paragraph(""));
            documento.add(new Paragraph("Total rentas de quinta categoría : " + txtRentaQuinta.getText()));
            documento.add(new Paragraph("Total rentas de cuarta y quinta categoría (Cas. 509 + Cas. 111) : " 
                    + lbl3.getText()));
            documento.add(new Paragraph("Deducción de 7 UIT (Hasta el límite resultante de la Cas. 510) : " 
                    + lbl4.getText()));
            documento.add(new Paragraph(""));
            documento.add(new Paragraph("TOTAL RENTA NETA DE CUARTA Y QUINTA CATEGORÍA Cas. 510 – Cas. 511 - Cas. ABC) : " 
                    + lbl5.getText()));
            documento.add(new Paragraph("Sub total Cas. 512 – (Cas. 522 + Cas. 519) : " + lbl6.getText()));
            documento.add(new Paragraph(""));
            documento.add(new Paragraph("Total Renta Imponible de Trabajo y Fuente Extranjera : " + lbl7.getText()));
            documento.add(new Paragraph("Impuesto a la Renta : " + lbl8.getText()));
            documento.add(new Paragraph(""));
            documento.add(new Paragraph(""));
            documento.add(new Paragraph("Saldo de la Deuda Tributaria: " + lbl9.getText()));
            documento.close();
            
            JOptionPane.showMessageDialog(null, "Archivo PDF creado correctamente", "Información",1);
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Atención",2);
        }
        
    }

    private void abrir(String nombre) {
        try {
            File path = new File(nombre + ".pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Atención",2);
            
        }
    }

    private void Limpiar() {
        txtNombre.setText("");
        txtCelular.setText("");
        txtRuc.setText("");
        lbl1.setText("");
        lbl2.setText("");
        txtRentaBruta.setText("");
        lbl3.setText("");
        lbl4.setText("");
        txtRentaQuinta.setText("");
        lbl5.setText("");
        lbl6.setText("");
        lbl7.setText("");
        lbl8.setText("");
        lbl9.setText("");
        txtRuc.requestFocus();
    }

        
    public class Reporte extends Thread {
        OperacionSunatView jf;
        String n_doc_declarante=txtRuc.getText();
        public Reporte(OperacionSunatView jf){
            this.jf=jf;
        }
        
        public void run(){
            int i=0;
            int j=0;
            try {
                Connection conn=ConectarSQLServer();
                String nombre_reporte="";
                Map reportParams = new HashMap();
                String query="select a.*,'Reporte' modelo from db_fisca_exp.dbo.declaraciones a\n" +
                "inner join (\n" +
                "select n_doc_declarante, max(n_orden)n_orden from db_fisca_exp.dbo.declaraciones\n" +
                "group by n_doc_declarante) b on a.n_doc_declarante=b.n_doc_declarante and a.n_orden=b.n_orden where a.n_doc_declarante='"+n_doc_declarante+"'";
                Statement stmt = conn.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                File dir_pdf;
                dir_pdf=new File(System.getProperty("user.dir")+"\\PDF");
                dir_pdf.mkdirs();
                while (rs.next()) {
                    nombre_reporte=rs.getString("n_doc_declarante").trim();
                    File file = new File(System.getProperty("user.dir")+"\\PDF\\"+nombre_reporte+".pdf");
                    reportParams.put("n_doc_declarante", rs.getString("n_doc_declarante"));
                                        new utilsJasperReport().reportePDF(file, "/modelos", rs.getString("modelo"), reportParams);
                    i++;                    
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
      }
    
    
   
    
}
